accounts/urls.py
from django.urls import path
from .views import (RegistrationView, IndexView,
                    UpdateUserView,UpdatePasswordView,
                    )
from django.contrib.auth.views import LoginView , LogoutView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('alterar-dados', UpdateUserView.as_view(), name='update_user'),
    path('alterar-senha', UpdatePasswordView.as_view(), name='update_password'),
    path('registro/', RegistrationView.as_view(), name='register'),
    path('entrar/',LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
]

checkout/urls.py
from django.urls import path



from .views import (CreateCartItemView,CartItemView,CheckoutView, 
                OrderListView, OrderDetailView, PagSeguroView,
                pagseguro_notification, PayPalView,
                
                )


urlpatterns = [
    path('carrinho/adicionar/<slug:slug>/',CreateCartItemView.as_view(),name='create_cart_item'),
    path('carrinho/',CartItemView.as_view(),name='cart_item_view'),
    path('carrinho/finalizar/',CheckoutView.as_view(),name='checkout_view'),
    path('meus-pedidos/',OrderListView.as_view(),name='order_list'),
    path('meus-pedidos/<int:pk>/',OrderDetailView.as_view(),name='order_detail'),
    path('finalizando/<int:pk>/pagseguro/',PagSeguroView.as_view(),name='pagseguro_view'),
    path('notificacoes/pagseguro/',pagseguro_notification,name='pagseguro_notification'),
    path('finalizando/<int:pk>/paypal/',PayPalView.as_view(),name='paypal_view'),

    
]

core/urls.py
from django.urls import path
from .views import  contact, IndexView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contato/', contact, name='contact'),
    
]

djangoecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('conta/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('catalogo/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('compras/', include(('checkout.urls','checkout'), namespace='checkout')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser,UserManager, PermissionsMixin
import re

class User(AbstractBaseUser, PermissionsMixin):
    
    username = models.CharField(
        "usuario", max_length=30, unique=True,validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_.'
                ,'invalid'

            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
        )
    name = models.CharField('Nome', max_length=150, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField("Equipe", default=False)
    is_active = models.BooleanField("Atívo", default=True)
    date_joined = models.DateTimeField('Data da Entrada', auto_now_add=True)


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    
    def get_full_name(self):
        return str(self)
    
    
    def get_short_name(self):
        return str(self).split(" ")[0]
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email','name','is_active', 'is_staff']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views.generic import (CreateView,TemplateView,
                                UpdateView,FormView,
                                )
from django.urls import reverse_lazy
from .forms import UserAdminCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm,PasswordResetForm



User = get_user_model()

class IndexView(LoginRequiredMixin,TemplateView):
    
    template_name = 'accounts/index.html'
    

class RegistrationView(CreateView):

    form_class =UserAdminCreationForm
    template_name = 'accounts/register.html'
    model = User
    success_url = reverse_lazy('index')


class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_user.html'
    fields=['name', 'email']
    success_url=reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user
    

class UpdatePasswordView(LoginRequiredMixin,FormView):
    
    template_name = 'accounts/update_password.html'
    success_url=reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs=super(UpdatePasswordView,self).get_form_kwargs()
        kwargs['user']=self.request.user
        return kwargs

    def form_valid(self,form):
        form.save()
        return super(UpdatePasswordView,self).form_valid(form)

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block title %}Minha Conta | {{ block.super }}{% endblock title %}
{% block container %}
      <div class="container margin-top">
        <ol class="breadcrumb">
          <li><a href="#">Início</a></li>
          <li class="active">Minha Conta</li>
        </ol>
        <div class="row">
            <div class="col-md-4">
                <div class="list-group">
                  <a href="#" class="list-group-item active">Minha Conta</a>
                  <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
                  <a href="{% url 'accounts:update_password' %}" class="list-group-item">Alterar Senha</a>
                  <a href="{% url 'checkout:order_list' %}" class="list-group-item">Meus Pedidos</a>
                </div>
            </div>
            <div class="col-md-8">
            {% block accounts_container %}
                <h2>Bem vindo, {{user}}</h2>
            {% endblock accounts_container %}
            </div>
        </div>
      </div>

{% endblock container %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Login | {{ block.super }}
{% endblock %}
{% block container %}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form method='post' class="form-horizontal">
        {% csrf_token %}

        {%for error in form.non_field_errors%}
            <div class="alert alert-danger">
                {{error}}
            </div>
        {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for=" {{form.username.auto_id}} " class="col-md-3 control-label">{{form.username.label}}</label>
                  <div class="col-md-9">
                  {%render_field form.username class="form-control"%}
                  {% for error in form.username.errors  %}
                    <span class='help-block'>{{error}}</span>
                  {% endfor %}
                  </div>
                </div>
                <div class="form-group {% if form.password.errors %}has-error{% endif %}">
                  <label for="{{form.password.auto_id}}" class="col-md-3 control-label">{{form.password.label}}</label>
                  <div class="col-md-9">
                  {%render_field form.password class="form-control"%}
                    {% for error in form.password.errors  %}
                    <span class='help-block'>{{error}}</span>
                  {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Entrar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

{% endblock container %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
    Registro | {{ block.super }}
{% endblock %}
{% block container %}

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="page-header">
                <h1>Registro</h1>
            </div>
            <form method='post' class="form-horizontal">
            {% csrf_token %}

            {%for error in form.non_field_errors%}
                <div class="alert alert-danger">
                    {{error}}
                </div>
            {% endfor %}
                <fieldset>
                    {% for field in form  %}
                    <div class="form-group{% if field.errors %} has-error{% endif %}">
                        <label for=" {{field.auto_id}} " class="col-md-3 control-label">{{field.label}}</label>
                        <div class="col-md-9">
                            {%render_field field class="form-control"%}
                            {% for error in field.errors  %}
                                <span class='help-block'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>

{% endblock container %}

accounts/templates/accounts/update_password.html
{% extends 'accounts/index.html' %}
{% load widget_tweaks %}


{% block title %}Alterar Senha{% endblock title %}

{% block accounts_container %}
    <form method='post' class="form-horizontal">
        {% csrf_token %}

        {%for error in form.non_field_errors%}
            <div class="alert alert-danger">
                {{error}}
            </div>
        {% endfor %}
            <fieldset>
                {% for field in form  %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                    <label for=" {{field.auto_id}} " class="col-md-3 control-label">{{field.label}}</label>
                    <div class="col-md-9">
                        {%render_field field class="form-control"%}
                        {% for error in field.errors  %}
                            <span class='help-block'>{{error}}</span>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
                
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </div>
            </fieldset>
    </form>

{% endblock accounts_container %}

accounts/templates/accounts/update_user.html
{% extends 'accounts/index.html' %}
{% load widget_tweaks %}


{% block title %}Alterar Dados{% endblock title %}

{% block accounts_container %}
    <form method='post' class="form-horizontal">
        {% csrf_token %}

        {%for error in form.non_field_errors%}
            <div class="alert alert-danger">
                {{error}}
            </div>
        {% endfor %}
            <fieldset>
                {% for field in form  %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                    <label for=" {{field.auto_id}} " class="col-md-3 control-label">{{field.label}}</label>
                    <div class="col-md-9">
                        {%render_field field class="form-control"%}
                        {% for error in field.errors  %}
                            <span class='help-block'>{{error}}</span>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
                
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </div>
            </fieldset>
    </form>

{% endblock accounts_container %}