accounts/urls.py
from django.urls import path
from .views import (RegistrationView, IndexView,
                    UpdateUserView,UpdatePasswordView,
                    )
from django.contrib.auth.views import LoginView , LogoutView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('alterar-dados', UpdateUserView.as_view(), name='update_user'),
    path('alterar-senha', UpdatePasswordView.as_view(), name='update_password'),
    path('registro/', RegistrationView.as_view(), name='register'),
    path('entrar/',LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
]

catalog/urls.py
from django.urls import path
from .views import ProductListView, CategoryListView, product


urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('<slug:slug>/', CategoryListView.as_view(), name='category'),
    path('produto/<slug:slug>/', product, name='product'),
]

checkout/urls.py
from django.urls import path



from .views import (CreateCartItemView,CartItemView,CheckoutView, 
                OrderListView, OrderDetailView, PagSeguroView,
                pagseguro_notification, PayPalView,
                
                )


urlpatterns = [
    path('carrinho/adicionar/<slug:slug>/',CreateCartItemView.as_view(),name='create_cart_item'),
    path('carrinho/',CartItemView.as_view(),name='cart_item_view'),
    path('carrinho/finalizar/',CheckoutView.as_view(),name='checkout_view'),
    path('meus-pedidos/',OrderListView.as_view(),name='order_list'),
    path('meus-pedidos/<int:pk>/',OrderDetailView.as_view(),name='order_detail'),
    path('finalizando/<int:pk>/pagseguro/',PagSeguroView.as_view(),name='pagseguro_view'),
    path('notificacoes/pagseguro/',pagseguro_notification,name='pagseguro_notification'),
    path('finalizando/<int:pk>/paypal/',PayPalView.as_view(),name='paypal_view'),

    
]

core/urls.py
from django.urls import path
from .views import  contact, IndexView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contato/', contact, name='contact'),
    
]

djangoecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('conta/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('catalogo/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('compras/', include(('checkout.urls','checkout'), namespace='checkout')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Django E-Commerce{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/extra.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                  {% for category in categories %}
                    <li><a href={{category.get_absolute_url}}>{{ category }}</a></li>
                  {% endfor %}
              </ul>
            </li>
			<li>
				<a href="{% url 'contact' %}">Contato</a>
			</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>Olá, {{user}}</li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:index' %}">Minha Conta</a></li>
                <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
              {% else %}
                <li><a href="{% url 'accounts:register' %}">Cadastrar</a></li>
                <li><a href="{% url 'accounts:login' %}">Minha Conta</a></li>
            {% endif %}
            
              <li><a href="{% url 'checkout:cart_item_view' %}">Carrinho</a></li>

          </ul>
        </div>
      </div>
    </div>
    <div class="container margin-top">
    {% block messages %}
      {% for message in messages %}
        <div class='alert alert-{{message.tags}}'>
          {{message}}
        </div>
      {% endfor %}
    {% endblock messages %}
		{% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="">Início</a></li>
			      <li><a href="">Produtos</a></li>
			      <li><a href="">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>