catalog/urls.py
from django.urls import path
from .views import ProductListView, CategoryListView, product


urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('<slug:slug>/', CategoryListView.as_view(), name='category'),
    path('produto/<slug:slug>/', product, name='product'),
]

checkout/urls.py
from django.urls import path



from .views import (CreateCartItemView,CartItemView,CheckoutView, 
                OrderListView, OrderDetailView, PagSeguroView,
                pagseguro_notification, PayPalView,
                
                )


urlpatterns = [
    path('carrinho/adicionar/<slug:slug>/',CreateCartItemView.as_view(),name='create_cart_item'),
    path('carrinho/',CartItemView.as_view(),name='cart_item_view'),
    path('carrinho/finalizar/',CheckoutView.as_view(),name='checkout_view'),
    path('meus-pedidos/',OrderListView.as_view(),name='order_list'),
    path('meus-pedidos/<int:pk>/',OrderDetailView.as_view(),name='order_detail'),
    path('finalizando/<int:pk>/pagseguro/',PagSeguroView.as_view(),name='pagseguro_view'),
    path('notificacoes/pagseguro/',pagseguro_notification,name='pagseguro_notification'),
    path('finalizando/<int:pk>/paypal/',PayPalView.as_view(),name='paypal_view'),

    
]

core/urls.py
from django.urls import path
from .views import  contact, IndexView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contato/', contact, name='contact'),
    
]

djangoecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('conta/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('catalogo/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('compras/', include(('checkout.urls','checkout'), namespace='checkout')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):

    name = models.CharField("Nome", max_length=100)
    slug= models.SlugField("Identificador", max_length=100)

    created = models.DateField("Criado em", auto_now_add=True)
    modified = models.DateField("Modificado em", auto_now_add=True)

    class Meta:
        verbose_name ='Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("catalog:category", kwargs={"slug": self.slug})
    

class Product(models.Model):

    name = models.CharField("Nome", max_length=100)
    slug= models.SlugField("Identificador", max_length=100)

    created = models.DateField("Criado em", auto_now_add=True)
    modified = models.DateField("Modificado em", auto_now_add=True)

    category = models.ForeignKey(Category, verbose_name='Categoria', on_delete=models.CASCADE)
    description = models.TextField('Descrição', blank=True)
    image=models.ImageField('Imagem',upload_to='products', blank=True, null=True)
    price = models.DecimalField('Preço', max_digits=8, decimal_places=2)
    
    class Meta:
        verbose_name ='Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']
    
    
    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"slug": self.slug})

catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from django.views import generic



class ProductListView(generic.ListView):
    
    model=Product
    template_name = 'catalog/product_list.html'
    paginate_by = 3


class CategoryListView(generic.ListView):
    
    template_name = 'catalog/category.html'
    context_object_name = 'products_list'
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(category__slug = self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_category"] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context 
    



def product(request,slug):
    template = 'catalog/product.html'
    products = Product.objects.get(slug=slug)
    context = {
        'product': products,
    }
    return render(request,template, context)

catalog/templates/catalog/_product.html
{% load thumbnail%}

<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <a href={{product.get_absolute_url}}>
            {% if product.image %}
                <img src="{{ product.image|thumbnail_url:'product_image' }}" alt=''/>
            {%else%}
                <img src="http://placehold.it/350x250" alt="" />
            {%endif%}
        </a>
        <div class="caption">
            <h3>{{product.name}}</h3>
            <p>{{product.description|linebreaks}}.</p>
            <p><a href={{product.get_absolute_url}} class="btn btn-success" role="button">Detalhes</a> 
            <a href="{% url 'checkout:create_cart_item' product.slug %}" class="btn btn-default" role="button">Adicionar ao Carrinho</a></p>
        </div>
    </div>
</div>

catalog/templates/catalog/category.html
{% extends "base.html" %}
{% load pagination %}

{% block title %}
    {{current_category}} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>{{current_category}}</h1>
</div>
<div class="row">
    {% for product in products_list %}
    {% include 'catalog/_product.html' %}
   {% endfor %}
</div>
{%pagination request paginator page_obj%}

{% endblock %}

catalog/templates/catalog/product.html
{% extends "base.html" %}

{% block title %}
    {{product}} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>{{product}}</h1>
</div>
<div class="row">
  <div class="col-sm-4">
      <a href="#" class="thumbnail">
        {% if product.image %}
          <img src="{{ product.image.url }}" alt=''/>
        {%else%}
          <img src="http://placehold.it/350x250" alt="" />
        {%endif%}
      </a>
  </div>

  <div class="col-sm-8">
  <p class='text-right'>
    <a href="{% url 'checkout:create_cart_item' product.slug %}" class="btn btn-default" role="button">Adicionar ao Carrinho</a></p>
      {{product.description|linebreaks}}
  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "base.html" %}
{% load pagination %}


{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Produtos</h1>
</div>
<div class="row">
    {% for product in product_list %}
    {% include 'catalog/_product.html' %}
    
   {% endfor %}
</div>
{%pagination request paginator page_obj%}
{% endblock %}